export const MESSAGES = {
  USER_EXISTS: 'User already exists',
  VERIFICATION_EMAIL_SENT: 'Verification email sent',
  ACCOUNT_CREATED:
    'Your account has been created successfully. Please verify your email to activate your account.',
  VERIFY_YOUR_ACCOUNT: 'Verify Your Account',
  RESET_PASSWORD: 'Reset Password',
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_VERIFIED: 'User is already verified',
  INVALID_TOKEN_REQUEST:
    'Verification failed. The link may be invalid or expired. Please request a new verification email.',
  ACCOUNT_VERIFIED:
    'Your account has been successfully verified. You can now log in.',
  INVALID_CREDENTIALS:
    'Authentication failed. Please check your credentials and try again.',
  INVALID_TOKEN: 'Invalid or expired token. Please request a new one.',
  LOGIN_SUCCESS: 'Login Successful',
  TOKEN_UPDATED: 'Token updated successfully',
  LOGOUT_SUCCESS: 'Logged out successfully',
  COMPANY_CREATED: 'Company created successfully',
  PLAN_NOT_FOUND: 'Price plan not found',
  NO_ACTIVE_SUBSCRIPTION: 'You do not have any active subscription.',
  ACTIVE_SUBSCRIPTION: 'You already have an active subscription.',
  CANCEL_SUCCESS: 'Your subscription has been cancelled successfully.',
  No_PAYMENT_METHODS: 'You have not saved any payment method.',
  PAYMENT_METHOD_REMOVED:
    'Payment method has been removed, please add other method to continue your subscription.',
  PROFILE_EXISTS: 'Profile already exists',
  PROFILE_CREATED: 'Profile has been created successfully.',
  PHONE_VERIFIED: 'Phone is already added, and verified.',
  PHONE_IN_USE: 'This number is already in use.',
  OTP_SENT: 'OTP has been sent, please verify.',
  PHONE_NOT_FOUND: 'Phone ot found.',
  INAVLID_CODE: 'Invalid code',
  PHONE_VERIFIED_SUCCESS: 'Your phone has been successfully verified.',
  PASSWORD_UPDATED: 'Your password has been updated successfully',
  INVALID_REQUEST: 'Invalid Request',
  PHONE_NOT_VERIFIED: 'You have not added or verified your phone.',
  OTP_EXPIRED: 'Your OTP has expired, please request for a new OTP.',
  TWO_FA_TOGGLED: 'Your 2 Factor Authentication has been updated successfully.',
  PROFILE_UPDATED: 'Your profile has been updated successfully',
  PROFESSIONALS_LIST: 'List of Professionals',
  BANK_DETAILS_EXISTED: 'You have already added bank details.',
  BANK_DETAILS_ADDED: 'Bank details have been successfully added.',
  BANK_DETAILS_UPDATED: 'Bank details have been successfully updated.',
  SHIFTS_LIST: 'List of Shifts',
  TIMESHEET_CREATED: 'Timesheet has been added successfully.',
  TIMESHEETS: 'Timesheets',
  TIMESHEET_REMOVED: 'Timesheet has been removed successfully.',
  OFFER_CREATED: 'Offer has been created successfully.',
  OFFER_UPDATED: 'Offer has been updated successfully.',
  PLANS_LIST: 'List of Plans',
  INVALID_PAYMENT_METHOD:
    'Unsupported payment method. Supported methods are: stripe, paypal.',
};

export const STATUSES = {
  INFO: 'info',
  SUCCESS: 'success',
  ERROR: 'error',
  PENDING: 'pending',
  ACTIVE: 'active',
  CANCELLED: 'cancelled',
  PAST_DUE: 'past_due',
  SUSPENDED: 'suspended',
};
